# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  deploy:
    docker:
      # specify the version you desire here
      - image: kmui2/rise-ci

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      - save_cache:
          paths:
            - node_modules
          key: v2-dependencies-{{ checksum "package.json" }}

      - add_ssh_keys
      - run:
          name: Deploy server to droplet
          command: |
            if [ "${CIRCLE_BRANCH}" == "deployment" ]; then
              ssh-keyscan 206.189.181.215 >> ~/.ssh/known_hosts
              sudo npm i -g pm2
              npm run deploy
            fi
workflows:
  version: 2
  build-deploy:
    jobs:
      - deploy